### ISSUE TITLE
Infografia sistemas numericos irwing

### ISSUE THREAD

**Issue by irwingsael** [SistemasTecTlaxiaco/infografia-irwingsael#1]
[Infografia sistemas numericos3.pdf](https://github.com/user-attachments/files/16859549/Infografia.sistemas.numericos3.pdf)

**Comment by kevinMazarelloJOSE** [comment]
redacción y ortografía : 14/14
exposición de ideas centrales : 16/16
organización de ideas centrales : 14/14
uso de imágenes y colores : 14/14
presentación visual : 14/14
referencias : 14/14
presentación : 14/14
calificación final : 20/20

**Comment by josealfredo79** [comment]
No puedo ver el trabajo..

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
